# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
FinancialProduct.create(name: 'Traditional IRA', description: 'A Traditional IRA may give you an immediate tax benefit because contributions are often tax deductible. With a Traditional IRA, up to $6,000 of tax deferred income may be placed in the IRA. Account owners may also contribute an additional $6,000 a year of earned income to a separate IRA for a non-income-earning spouse. Account owners who are age 50 or over are allowed to contribute an additional $1,000.
    Taxable distributions from an IRA can be taken without penalty starting at age 59½ and must be started by April 1st of the year following the year the account owner reaches 72, unless you turned 70½ prior to January 1, 2020. If this is the case, you must begin taking distributions starting April 1st of the year following the age the account owner reaches 70½.')
FinancialProduct.create(name: 'Roth IRA', description: 'A Roth IRA’s tax advantages differ from the Traditional IRA. If eligible for this account, your annual contribution limits are the same but are not tax deductible. However, since annual contributions have already been taxed, these contributions will never be taxed again and earnings can grow tax free. Finally, the contributed funds can be withdrawn any time you wish and there are no required minimum distributions.
    Withdrawals
    Withdrawals of your contributions to a Roth IRA are tax-free anytime. However, withdrawals of earnings are only free from federal income tax, provided they meet the following requirements:
    You are purchasing your first home ($10,000 lifetime maximum)
    The Roth IRA has been in existence for at least five years
    You are age 59½ or older
    You become disabled or have passed away
    What You Should Know About Converting Costs
    You can convert a Traditional IRA to a Roth IRA at any time. You must note that when you convert to a Roth IRA, you must pay income tax on the otherwise taxable amount of the transfer. To maximize the benefits of conversion, the money to pay those taxes should come from a source outside the Traditional IRA you are converting. You may convert your Traditional IRA over several years to manage the tax consequences.') 
FinancialProduct.create(name: 'Individual', description: 'An individual account is a standard brokerage account with only one owner.')
FinancialProduct.create(name: '529', description: "A 529 Plan is a great way to save for college and gain tax benefits. It allows you to save for college while your money grows tax-deferred. The 529 Plan is designed to meet the needs of virtually every family and every budget.  There is no minimum annual contribution required with a 529 Plan.  What is a 529? Section 529 college savings plans are established by states under section 529(b)(A)(ii) of the Internal Revenue Code as 'qualified tuition programs' through which individuals make investments for the purpose of accumulating savings for qualifying higher education costs of beneficiaries.  Choices vary by individual plan and also by state, and may be limited. Details are available in the plan's enrollment handbook.")
FinancialProduct.create(name: 'Coverdell ESA', description: "The Coverdell ESA is a savings plan created for the purpose of paying a student's qualified educational expenses. These can include, but are not limited to, tuition, books, and uniforms. Like a 529, your money is tax-deferred, allowing your fund to grow faster.  Contributions to a Coverdell ESA are not tax-deductible. In addition, contributions are allowed for individuals under the age of 18.  Distributions from a Coverdell ESA may be tax-free, but they must be used to pay for qualified educational expenses.  With a Coverdell ESA account, you can invest in a wide variety of products including stocks, bonds, and mutual funds.  The maximum contribution per year is $2,000.")
FinancialProduct.create(name: 'Trust', description: "A Trust account allows the account owner to transfer assets to one or more recipients, called trustees, who hold legal title to the transferred assets and manage the assets for the benefit of the owner or other named beneficiaries. TD Ameritrade offers legally established taxable living, revocable, irrevocable and testamentary trusts. They must already have the trust created by an Attorney and then they may open a brokerage account with TD Ameritrade.")
FinancialProduct.create(name: 'Trust', description: "A Trust account allows the account owner to transfer assets to one or more recipients, called trustees, who hold legal title to the transferred assets and manage the assets for the benefit of the owner or other named beneficiaries. TD Ameritrade offers legally established taxable living, revocable, irrevocable and testamentary trusts. They must already have the trust created by an Attorney and then they may open a brokerage account with TD Ameritrade.")
client = IEX::Api::Client.new(
    publishable_token: 'pk_02f29690e23d4897b4b7916f6e78d39e',
    secret_token: 'sk_a74468b214424b4c825232000f18608c',
    endpoint: 'https://cloud.iexapis.com/v1'
  )